"""baseline_with_timestamps_constraints_snapshots

Revision ID: 4e3ba1b85a1f
Revises: 
Create Date: 2026-03-13 22:23:46.264637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3ba1b85a1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lol_rank_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('queue_type', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('lp', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['lol_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lol_rank_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lol_rank_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lol_rank_snapshots_profile_id'), ['profile_id'], unique=False)

    op.create_table('sc2_rank_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('queue_type', sa.String(), nullable=False),
    sa.Column('mmr', sa.Integer(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['sc2_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sc2_rank_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sc2_rank_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sc2_rank_snapshots_profile_id'), ['profile_id'], unique=False)

    with op.batch_alter_table('lol_masteries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_lol_mastery_profile_champion', ['profile_id', 'champion_id'])

    with op.batch_alter_table('lol_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Integer(), nullable=True))

    with op.batch_alter_table('lol_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))

    with op.batch_alter_table('lol_ranks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_lol_rank_profile_queue', ['profile_id', 'queue_type'])

    with op.batch_alter_table('sc2_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))

    with op.batch_alter_table('sc2_ranks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_sc2_rank_profile_season_race_queue', ['profile_id', 'season', 'race', 'queue_type'])

    with op.batch_alter_table('sc2_raw_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc2_raw_data', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sc2_ranks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sc2_rank_profile_season_race_queue', type_='unique')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sc2_profiles', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('lol_ranks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lol_rank_profile_queue', type_='unique')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('lol_profiles', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('lol_matches', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('lol_masteries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lol_mastery_profile_champion', type_='unique')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sc2_rank_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sc2_rank_snapshots_profile_id'))
        batch_op.drop_index(batch_op.f('ix_sc2_rank_snapshots_id'))

    op.drop_table('sc2_rank_snapshots')
    with op.batch_alter_table('lol_rank_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lol_rank_snapshots_profile_id'))
        batch_op.drop_index(batch_op.f('ix_lol_rank_snapshots_id'))

    op.drop_table('lol_rank_snapshots')
    # ### end Alembic commands ###
